### ISSUE TITLE
incorrect usage of "neither" on repo's front page

### ISSUE THREAD

**Issue by masukomi** [slowernews/slowernews#1]
On the front page of this repo, in the readme and in the description line at the top both use "neither" when they should use "or".

"Neither" should always be paired with "nor".  For example "Neither X nor Y are acceptable to me." 

> Don't miss out neither spend a shit-ton of time distilling trivia.

Should read "Don't miss out, or spend a shit-ton of time distilling trivia."

OR alternately, 

"Neither miss out, nor spend a shit-ton of time distilling trivia."

Unfortunately that doesn't read as well. It really wants something _before_ the neither to. 

Additionally, it's not clear from the sentence what you're missing out on. 

So....

"With Slower News you neither miss out [on ?????], nor spend a shit-ton of time distilling trivia."

**Comment by slowernews** [comment]
Thanks for the corrections, I'm not an native English speaker... So, as I understand, it's fine like this:

"Don't miss out on trends or spend a shit-ton of time distilling trivia."
