### ISSUE TITLE
RSS feed broken: error on line 8 at column 30: xmlParseEntityRef: no name

### ISSUE THREAD

**Issue by d-e-s-o** [slowernews/slowernews#13]
![slower](https://user-images.githubusercontent.com/6610056/105638333-f9f0ad00-5e26-11eb-997c-6402a85b6b60.png)

**Comment by slowernews** [comment]
@d-e-s-o

Thanks for letting me know, it should work now. I just simplified RSS feed it a bit to lower errors probability. It's hand coded so mistakes happen frequently. I use to test it in Feedly but its engine is very fault tolerant so I don't catch errors right away...

**Comment by d-e-s-o** [comment]
Thank you!
