### ISSUE TITLE
RSS is broken

### ISSUE THREAD

**Issue by lyz-code** [slowernews/slowernews#14]
Hey, thanks for the site, I've been looking for something similar for a long time.

I'd like to consume the updates through [RSS](https://www.slowernews.com/rss.xml), but it's giving me the following error:

```
XML Parsing Error: mismatched tag. Expected: </p>.
Location: https://www.slowernews.com/rss.xml
Line Number 9, Column 138:
			<description><p>Some people asked for a place where they could leave their email and receive all updates on Slower News. Here it is!</description>
```

Thanks!

**Comment by Ninguem** [comment]
Sim - o internacional. O português parece estar bem.

**Comment by slowernews** [comment]
@lyz-code @Ninguem 

Easy fix, it should work now. I only test it on Feedly and its RSS engine is very permissive.

**Comment by lyz-code** [comment]
It works perfectly, thanks! :)

**Comment by Ninguem** [comment]
Agora não acedo ao português!
:-P

**Comment by slowernews** [comment]
@Ninguem 

The demand (you were the first to complain) didn't justify the hassle (it was hand made) so I deprecated Portugal page RSS. The page link also changed: [Slowernews - Portugal](https://www.slowernews.com/s/portugal).

Anyway, it might change in the future if the demand justifies it.
