### ISSUE TITLE
Long-news graphs?

### ISSUE THREAD

**Issue by matthewmiaow** [slowernews/slowernews#16]
I think another great idea might be to embed several graphs of long-term global trends. 

So for example:

<iframe src="https://ourworldindata.org/grapher/share-of-people-who-say-they-are-happy" loading="lazy" style="width: 100%; height: 600px; border: 0px none;"></iframe>

I'm happy to compile a list of these. Topics could be: CO2 levels, inequality, global happiness, global wealth, poverty, hunger, computing power... etc etc. 

I think this might aid the whole longer-term perspective goals of slow news?

**Comment by slowernews** [comment]
Hi Matthew. Slower News is text-only (for now at least). A text link to relevant and somewhat surprising (anyway these are still "news") graphs would fit better. Something like:

[Despite pessimistic media portrays, people are generally happier today than 20 years ago.](https://ourworldindata.org/grapher/share-of-people-who-say-they-are-happy)

You can also consider starting a [specific page](https://github.com/slowernews/slowernews/tree/master/s) on a subject that is interesting to you  - it certainly would be interesting to others. There isn't a CMS neither I plan to add one soon. Dealing with raw HTML acts as a filter: having abandoned pages is not nice. Please think carefully and make offline experiments first. [Some ideas](https://github.com/slowernews/slowernews#footnote3).

Cheers
