### ISSUE TITLE
RSS feed is invalid

### ISSUE THREAD

**Issue by VoidMonk** [slowernews/slowernews#17]
The feed (https://www.slowernews.com/rss.xml) linked on the homepage is not a valid RSS feed: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.slowernews.com%2Frss.xml, hence it fails to be parsed in most feed readers. It's mainly due to use of raw HTML tags in the description. You can wrap the markup in CDATA to fix the issue.

**Comment by slowernews** [comment]
Thanks for pointing it (the error and the solution). This RSS feed is handmade and I only use to test it on Feedly (very permissive).

According to [the validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.slowernews.com%2Frss.xml) it should work now. If not please let me know.

**Comment by VoidMonk** [comment]
Thanks, all good.
