### ISSUE TITLE
Selecting <a> text looks blurry

### ISSUE THREAD

**Issue by Ryuuji159** [slowernews/slowernews#2]
I frequently select text while I read but in this page it appears blurry as the image shows.

I'm using Firefox

![image](https://user-images.githubusercontent.com/17039188/76447233-1585cd00-63a7-11ea-9579-de339b403c5c.png)

**Comment by slowernews** [comment]
I'm aware of it. That's the side effect of not using the standard underline on links. The standard link underline is continuous and this is aware of letters like "p", "y, "g", etc.

**Comment by itsrainingmani** [comment]
I think this can be solved by using the `::selection` selector.

```css
::selection {
  color: white;
  background: black;
  text-shadow: none;
}
```

This yields the following result - 

![image](https://user-images.githubusercontent.com/10191300/76453879-09e7d580-63aa-11ea-936b-b113eeb2387d.png)

**Comment by itsrainingmani** [comment]
I've submitted a pull request to take care of this issue. Hope that is ok :-)

**Comment by slowernews** [comment]
Thank you Manikandan! Merged.

**Comment by itsrainingmani** [comment]
Glad I could help!
